#!/usr/bin/env bash

#
# This script finds and classifies JBoss AS instances by specific community and
# enterprise releases.
# 
# Classification is simple: search for jboss-modules.jar and run.jar files and
# then extract the version from the pom.properties and MANIFEST.MF,
# respectively, to determine which distribution contained the jar
#
# NB:  This script is up to date through EAP 6.4 CP23, EAP 7.0 CP09,
#     EAP 7.1 CP06, EAP 7.2 CP09, EAP 7.3 CP07, EAP 7.4 Beta, and
#     WildFly 24.0.0.Beta1

# abort if error
set -e

# default arguments for the scanning module
WorkDir=/tmp
ClassificationFile=scan-jboss-classifier.txt.$$
MatchingReleaseFile=scan-jboss-release-list.$$
SearchRoot=/
#SearchRoot=/Users/rlucente/development/git/ansible-scan-jboss/test-distros

# get overrides for the above arguments from ansible
# this is potentially dangerous as arbitrary command execution can occur
if [ $# -gt 0 ]
then
  source ${1}
fi

# switch to scratch directory
pushd ${WorkDir} &> /dev/null

  # populate the classifier file used to match the jboss release
  #
  # this file is simply formatted as:
  # release-name ':' version-string
  #
  # where version-string refers to the jboss-modules.jar version or the
  # Implementation-Version in the run.jar MANIFEST.MF file.
  #
  # there can be multiple versions if jboss-modules.jar was patched
  #
  cat > ${ClassificationFile} <<EOF1
community/jboss-3.0.0: JBoss_3_0_0
community/jboss-3.0.1: JBoss_3_0_1
community/jboss-3.0.2: JBoss_3_0_2
community/jboss-3.0.3: JBoss_3_0_3
community/jboss-3.0.4: JBoss_3_0_4
community/jboss-3.0.5: JBoss_3_0_5
community/jboss-3.0.5RC1: JBoss_3_0_5_RC1
community/jboss-3.0.6: JBoss_3_0_6
community/jboss-3.0.7: JBoss_3_0_7
community/jboss-3.0.8: JBoss_3_0_8
community/jboss-3.2.1: JBoss_3_2_1
community/jboss-3.2.2: JBoss_3_2_2
community/jboss-3.2.2RC1: JBoss_3_2_2_RC1
community/jboss-3.2.2RC2: JBoss_3_2_2_RC2
community/jboss-3.2.2RC3: JBoss_3_2_2_RC3
community/jboss-3.2.2RC4: JBoss_3_2_2_RC4
community/jboss-3.2.3: JBoss_3_2_3
community/jboss-3.2.3RC1: JBoss_3_2_3_RC1
community/jboss-3.2.4: JBoss_3_2_4
community/jboss-3.2.4RC1: JBoss_3_2_4_RC1
community/jboss-3.2.4RC2: Branch_3_2
community/jboss-3.2.5: JBoss_3_2_5
community/jboss-3.2.6: JBoss_3_2_6
community/jboss-3.2.7: JBoss_3_2_7
community/jboss-3.2.8.SP1: JBoss_3_2_8_SP1
community/jboss-4.0.0: JBoss_4_0_0
community/jboss-4.0.1sp1: JBoss_4_0_1_SP1
community/jboss-4.0.2: JBoss_4_0_2
community/jboss-4.0.3SP1: JBoss_4_0_3_SP1
community/jboss-4.0.4.GA: JBoss_4_0_4_GA
community/jboss-4.0.5.GA: Branch_4_0
community/jboss-4.2.0.GA: JBoss_4_2_0_GA
community/jboss-4.2.1.GA: JBoss_4_2_1_GA
community/jboss-4.2.2.GA: JBoss_4_2_2_GA
community/jboss-4.2.3.GA: JBoss_4_2_3_GA
community/jboss-5.0.0.Beta1: JBoss_5_0_0_Beta1
community/jboss-5.0.0.Beta2: JBoss_5_0_0_Beta2
community/jboss-5.0.0.Beta3: JBoss_5_0_0_Beta3
community/jboss-5.0.0.Beta4: JBoss_5_0_0_Beta4
community/jboss-5.0.0.CR1: JBoss_5_0_0_CR1
community/jboss-5.0.0.GA: JBoss_5_0_0_GA
community/jboss-5.0.1.GA: JBoss_5_0_1_GA
community/jboss-5.1.0.Beta1: JBoss_5_1_0_Beta1
community/jboss-5.1.0.CR1: JBoss_5_1_0_CR1
community/jboss-5.1.0.GA: JBoss_5_1_0_GA
community/jboss-6.0.0.M1: JBoss_6_0_0_M1
community/jboss-6.0.0.M2: JBoss_6.0.0.20100216-M2
community/jboss-7.0.0.Alpha1: 1.0.0.Beta11
community/jboss-7.0.0.Beta1: 1.0.0.Beta16
community/jboss-7.0.0.Beta2: 1.0.0.Beta17
community/jboss-7.0.0.CR1: 1.0.0.CR4
community/jboss-as-7.0.0.Final: 1.0.1.GA
community/jboss-as-7.0.2.Final: 1.0.2.GA
community/jboss-as-7.1.0.Beta1b: 1.1.0.CR4
community/jboss-as-7.1.0.CR1b: 1.1.0.CR6
community/jboss-as-7.1.0.Final: 1.1.1.GA
community/jboss-as-distribution-6.0.0.20100429-M3: JBoss_6.0.0.20100429-M3
community/jboss-as-distribution-6.0.0.20100721-M4: JBoss_6.0.0.20100721-M4
community/jboss-as-distribution-6.0.0.20100911-M5: JBoss_6.0.0.20100911-M5
community/jboss-as-distribution-6.0.0.20101110-CR1: JBoss_6.0.0.20101110-CR1
community/jboss-as-distribution-6.0.0.Final: JBoss_6.0.0.Final
community/jboss-as-distribution-6.1.0.Final: JBoss_6.1.0.Final
community/wildfly-10.0.0.Beta1: 1.4.3.Final
community/wildfly-10.0.0.CR1: 1.4.4.Final
community/wildfly-10.0.0.CR5: 1.5.0.Final
community/wildfly-10.0.0.Final: 1.5.1.Final
community/wildfly-10.1.0.CR1: 1.5.2.Final
community/wildfly-11.0.0.Alpha1: 1.6.0.Beta6
community/wildfly-11.0.0.Beta1: 1.6.0.CR2
community/wildfly-11.0.0.CR1: 1.6.0.Final
community/wildfly-11.0.0.Final: 1.6.1.Final
community/wildfly-12.0.0.CR1: 1.7.0.Final
community/wildfly-13.0.0.Beta1: 1.8.5.Final
community/wildfly-14.0.0.Final: 1.8.6.Final
community/wildfly-15.0.0.Final: 1.8.7.Final
community/wildfly-16.0.0.Beta1: 1.9.0.Final
community/wildfly-17.0.0.Beta1: 1.9.1.Final
community/wildfly-19.0.0.Beta1: 1.9.2.Final
community/wildfly-19.0.0.Beta3: 1.10.0.Final
community/wildfly-20.0.0.Final: 1.10.1.Final
community/wildfly-21.0.0.Beta1: 1.10.2.Final
community/wildfly-22.0.0.Final: 1.11.0.Final
community/wildfly-8.0.0.Alpha1: 1.2.0.Final
community/wildfly-8.0.0.Alpha2: 1.2.2.Final
community/wildfly-8.0.0.Alpha3: 1.2.4.Final
community/wildfly-8.0.0.Alpha4: 1.3.0.Beta3
community/wildfly-8.0.0.Beta1: 1.3.0.Final
community/wildfly-8.1.0.CR1: 1.3.3.Final
community/wildfly-9.0.0.Alpha1: 1.3.4.Final
community/wildfly-9.0.0.Beta1: 1.4.2.Final
enterprise/jboss-4.2.0.GA_CP02: JBPAPP_4_2_0_GA_CP02
enterprise/jboss-4.2.0.GA_CP03: JBPAPP_4_2_0_GA_CP03
enterprise/jboss-4.2.0.GA_CP04: JBPAPP_4_2_0_GA_CP04
enterprise/jboss-4.2.0.GA_CP05: JBPAPP_4_2_0_GA_CP05
enterprise/jboss-4.2.0.GA_CP06: JBPAPP_4_2_0_GA_CP06
enterprise/jboss-4.2.0.GA_CP07: JBPAPP_4_2_0_GA_CP07
enterprise/jboss-4.2.0.GA_CP08: JBPAPP_4_2_0_GA_CP08
enterprise/jboss-4.2.0.GA_CP09: JBPAPP_4_2_0_GA_CP09
enterprise/jboss-4.3.0.GA_CP01: JBPAPP_4_3_0_GA_CP01
enterprise/jboss-4.3.0.GA_CP02: JBPAPP_4_3_0_GA_CP02
enterprise/jboss-4.3.0.GA_CP03: JBPAPP_4_3_0_GA_CP03
enterprise/jboss-4.3.0.GA_CP04: JBPAPP_4_3_0_GA_CP04
enterprise/jboss-4.3.0.GA_CP05: JBPAPP_4_3_0_GA_CP05
enterprise/jboss-4.3.0.GA_CP06: JBPAPP_4_3_0_GA_CP06
enterprise/jboss-4.3.0.GA_CP07: JBPAPP_4_3_0_GA_CP07
enterprise/jboss-4.3.0.GA_CP08: JBPAPP_4_3_0_GA_CP08
enterprise/jboss-EAP-4.2.0.GA_CP01: JBPAPP_4_2_0_GA_CP01
enterprise/jboss-eap-4.2.0-1.ep1.1: JBPAPP_4_2_0_GA
enterprise/jboss-eap-4.3.0.GA-1.ep1.8: JBPAPP_4_3_0_GA
enterprise/jboss-eap-5.0.0.GA: JBPAPP_5_0_0_GA
enterprise/jboss-eap-5.0.1: JBPAPP_5_0_1
enterprise/jboss-eap-5.1.0: JBPAPP_5_1_0
enterprise/jboss-eap-5.1.1: JBPAPP_5_1_1
enterprise/jboss-eap-5.1.2: JBPAPP_5_1_2
enterprise/jboss-eap-5.2.0: JBPAPP_5_2_0
enterprise/jboss-eap-6.0.0: 1.1.2.GA-redhat-1
enterprise/jboss-eap-6.0.1: 1.1.3.GA-redhat-1
enterprise/jboss-eap-6.1.0: 1.2.0.Final-redhat-1
enterprise/jboss-eap-6.1.1: 1.2.2.Final-redhat-1
enterprise/jboss-eap-6.2.0: 1.3.0.Final-redhat-2
enterprise/jboss-eap-6.2.2: 1.3.3.Final-redhat-1
enterprise/jboss-eap-6.3.1-patch: 1.3.4.Final-redhat-1
enterprise/jboss-eap-6.3.3-patch: 1.3.5.Final-redhat-1
enterprise/jboss-eap-6.4.0: 1.3.6.Final-redhat-1
enterprise/jboss-eap-6.4.10-patch: 1.3.7.Final-redhat-1
enterprise/jboss-eap-6.4.14-patch: 1.3.8.Final-redhat-1
enterprise/jboss-eap-6.4.16-patch: 1.3.9.Final-redhat-1
enterprise/jboss-eap-6.4.17-patch: 1.3.10.Final-redhat-1
enterprise/jboss-eap-6.4.21-patch: 1.3.11.Final-redhat-1
enterprise/jboss-eap-7.0.0: 1.5.1.Final-redhat-1
enterprise/jboss-eap-7.0.6-patch: 1.5.3.Final-redhat-1
enterprise/jboss-eap-7.0.7-patch: 1.5.4.Final-redhat-1
enterprise/jboss-eap-7.1.0.Alpha: 1.6.0.Beta6-redhat-1
enterprise/jboss-eap-7.1.0.Beta: 1.6.0.Beta9-redhat-1
enterprise/jboss-eap-7.1.0: 1.6.0.Final-redhat-1
enterprise/jboss-eap-7.1.3-patch: 1.6.4.Final-redhat-1
enterprise/jboss-eap-7.1.5-patch: 1.6.5.Final-redhat-00001
enterprise/jboss-eap-7.1.6-patch: 1.6.7.Final-redhat-00001
enterprise/jboss-eap-7.2.0.Beta: 1.8.5.Final-redhat-1
enterprise/jboss-eap-7.2.0: 1.8.6.Final-redhat-00001
enterprise/jboss-eap-7.2.2-patch: 1.8.8.Final-redhat-00001
enterprise/jboss-eap-7.2.8-patch: 1.8.9.Final-redhat-00001
enterprise/jboss-eap-7.2.9-patch: 1.8.10.Final-redhat-00001
enterprise/jboss-eap-7.3.0: 1.9.1.Final-redhat-00001
enterprise/jboss-eap-7.3.1-patch: 1.10.0.Final-redhat-00001
enterprise/jboss-eap-7.3.5-patch: 1.11.0.Final-redhat-00001
enterprise/jbossas-4.3.0.GA_CP10: JBPAPP_4_3_0_GA_CP10
EOF1

  touch $MatchingReleaseFile
  MODDIR="META-INF/maven/org.jboss.modules/jboss-modules"

  # find every occurrence of the modules jar in the filesystem (excluding
  # redundant copies from patching)
  for jar in `find ${SearchRoot} -type f -name 'jboss-modules.jar' | \
                 grep -v '\.installation/patches'`
  do
    jar xf ${jar} ${MODDIR}/pom.properties
    VERSION=$(unzip -p ${jar} ${MODDIR}/pom.properties | grep version | sed 's/version=//g')

    if [ ! -z "${VERSION}" ]
    then
      FOUND=`grep ${VERSION}\$ ${ClassificationFile} | cut -d':' -f1`

      if [ -z "${FOUND}" ]
      then
        FOUND="Unknown-JBoss-Release"
      fi

      echo "$FOUND: $VERSION in $jar"

      for fnd in `echo $FOUND`
      do
        echo ${fnd} >> ${MatchingReleaseFile}
      done

      rm -fr META-INF
    fi
  done

  # find every occurrence of the run jar in the filesystem
  for runjar in `find ${SearchRoot} -type f -name 'run.jar'`
  do
    VERSION=$(unzip -p ${runjar} META-INF/MANIFEST.MF | grep -A1 Implementation-Version | \
      tr '\r\n' ' ' | sed 's/..*[CS]V[SN]Tag[:=]//g' | sed 's/d   ate[=:]..*//g' | \
      sed 's/da   te[=:]..*//g' | sed 's/date[=:]..*//g' | sed 's/Date[=:]..*//g' | \
      sed 's/  *//g' | rev | cut -d/ -f1 | rev)
    if [ ! -z "${VERSION}" ]
    then

      FOUND=$(grep ${VERSION}\$ ${ClassificationFile} | cut -d':' -f1)

      if [ -z "${FOUND}" ]
      then
        FOUND="Unknown-JBoss-Release"
      fi

      echo "$FOUND: $VERSION in $runjar"

      for fnd in `echo $FOUND`
      do
        echo ${fnd} >> ${MatchingReleaseFile}
      done

      rm -fr META-INF
    fi
  done

  RELEASE_LIST=`sort -u ${MatchingReleaseFile} | tr '\n' ',' | sed 's/,/, /g' | sed 's/, $//g'`
  rm -f ${ClassificationFile} ${MatchingReleaseFile}

popd &> /dev/null

echo -n "hostname=`hostname` "
echo -n "cores=`grep 'cpu cores' /proc/cpuinfo | awk '{s+=$4} END {print s}'` "
echo "release=\"${RELEASE_LIST}\" changed=False"
exit 0
